# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('value', models.CharField(max_length=10)),
                ('answer', models.CharField(max_length=500)),
                ('theRound', models.CharField(max_length=100)),
                ('showNumber', models.IntegerField()),
                ('airDate', models.DateTimeField()),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
