# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='similarityClusterNum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='testClusterNum',
            field=models.IntegerField(default=0),
        ),
    ]
